language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install coveralls
  - pip install coverage
  - pip install mock
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover

after_success:
  - - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then coveralls
