build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.11"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "32"


init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install coveralls"
  - "%PYTHON%/Scripts/pip.exe install coverage"
  - "%PYTHON%/Scripts/pip.exe install mock"
  - "%PYTHON%/Scripts/pip.exe install -r ./requirements.txt"

test_script:
  - "%PYTHON%/Scripts/coverage run -m unittest discover"
